test: support for STREAMR_DOCKER_DEV_HOST env var
streamr-dev/streamr-client-javascript pull request #246
Opened 2021-04-30 08:06 UTC by harbu

Use same convention as in broker https://github.com/streamr-dev/broker/pull/233

2021-04-30 21:05 UTC, timoxley requested changes
oh dear

2021-04-30 21:05 UTC, timoxley commented on test/integration/config.js
> +        restUrl: process.env.REST_URL || `http://${process.env.STREAMR_DOCKER_DEV_HOST || localhost}/api/v1`,
`localhost` probably should be quoted

2021-04-30 21:05 UTC, timoxley commented on test/integration/config.js
> +            url: `http://${process.env.STREAMR_DOCKER_DEV_HOST || 10.200.10.1}:8891`
'10.200.10.1' should probably quoted

2021-04-30 21:05 UTC, timoxley commented on test/integration/config.js
> +            url: process.env.SIDECHAIN_URL || `http://${process.env.STREAMR_DOCKER_DEV_HOST || 10.200.10.1}:8546`,
Same

2021-04-30 21:05 UTC, timoxley commented on test/integration/config.js
> +            url: process.env.ETHEREUM_SERVER_URL || `http://${process.env.STREAMR_DOCKER_DEV_HOST || 10.200.10.1}:8545`,
whoops

2021-05-03 08:04 UTC, harbu commented on test/integration/config.js
> +        restUrl: process.env.REST_URL || `http://${process.env.STREAMR_DOCKER_DEV_HOST || localhost}/api/v1`,
ah crap should've tested this before PR

2021-05-07 13:21 UTC, harbu commented
Fixed quotes @timoxley

2021-05-10 12:26 UTC, merged